### PR TITLE
Only last configuration is used for each topic

### PR DESCRIPTION
**Pull request by walnut-tom**

### CODE REVIEW

**Comment by stephane-martin** [comment]
If you look at the configuration example file, in each [[mapping]] section, there is only *one* association `topic` => `configuration`. That's why "only last configuration is used" in the code.

Why proceding like that ? Because in golang maps are not ordered. When you loop over a map (with something like `for k, v := range m`), the (k, v) items are given in random choice.

But in kafka2influxdb configuration, we do want some order :

`onetopic` => `configuration1`                        // onetopic uses configuration1
`*` => `default_configuration`                         // every other topic uses default_configuration

has different meaning than

`*` => `default_configuration`                         // all topics will use default_configuration
`onetopic` => `configuration1`

So, if you write your configuration like that:
```
[[mapping]]
onetopic: configuration1
'*': default_configuration
```

Then it will be translated as a map in golang, and each time you run kafka2influxdb you get a different result.

Instead, write like that:

```
[[mapping]]
onetopic: configuration1

[[mapping]]
'*': default_configuration
```
That we be translated a in an (ordered !) array of maps, with only one k,v in each map.

So I believe the original code is correct.

**Comment by walnut-tom** [comment]
my config file is [kafka2influxdb.toml](https://github.com/walnut-tom/kafka2influxdb/blob/dat-json/kafka2influxdb.toml) , and modify  NewParser as
```
func NewParser(format string, precision string) Parser {
	if format == "json" {
		return JsonParser{precision: precision}
	} else if format == "dat-json" {
		return DatJsonParser{precision: precision}
	} else {
		return LineProtocolParser{precision: precision}
	}
}
```
the Parser is not DatJsonParser but JsonParser

**Comment by stephane-martin** [comment]
For each message retrieved from kafka, the configured mappings are tried, in the order of the configuration file.

You have two mappings: '*' => ... and 'app-dat' => ...

So for each message, the '*' glob is tried on the message topic. It matches, always. The second mapping is never tried.

So write instead:

```
[[mapping]]
"app-dat" = "dat-log"
[[mapping]]
  "*" = "default"
```

This means: "if the topic is 'app-dat', use 'dat-log' configuration. Else, use 'default' configuration".

**Comment by walnut-tom** [comment]
This is OK,but the configuration file must be in order.

**Pull request closed without merging**
