### PR TITLE
Retry and backoff for initial ping to influxdb

### PR DESCRIPTION
**Pull request by ryanjeffries**
To gracefully handle initial startup, added retry and back off to the initial influxdb ping.

### CODE REVIEW

**Comment by stephane-martin** [comment]
Hello,

why do you need it ? I mean, if the Ping fails, the error will be caught in the main loop in the `do_start_real` func in main.go, and the app will be restarted anyway.

**Comment by ryanjeffries** [comment]
Hi,

Great job on this kafka consumer, it is really helpful. While running kafka2influxdb in a docker container with either docker-compose or on kubernetes, if the iniital ping fails, the application exits with an error code and the container dies. The backoff / retry was an attempt to solve this while adhering to https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c

**Comment by stephane-martin** [comment]
-   it was a bug. please try again with master.
    refs:
    -   https://github.com/stephane-martin/kafka2influxdb/commit/154afc2357634fffd6be1053387bdb6e73c63e0c
    -   https://github.com/stephane-martin/kafka2influxdb/commit/803da7f5bbea065f1f4c40b06b178767b6a78631

- for 12 factor i'd like to make it possible to get the configuration from consul KV, not just from configuration files. Would that help ?

**Comment by ryanjeffries** [comment]
Thank you for the change. Having the ability to use both config file and KV would be good. I plan on using this in kubernetes which handles configs easily enough.

**Comment by stephane-martin** [comment]
https://github.com/stephane-martin/kafka2influxdb/commit/9b44dd37107f42da2fefac9be6302c8dafac74e5 can help too: with --watchconf flag kafka2influxdb will watch the configuration file and reload on change.

**Comment by stephane-martin** [comment]
@ryanjeffries first try for configuration in Consul has been pushed to master.

**Pull request closed without merging**
