### PR TITLE
metrics sent to influx

### PR DESCRIPTION
**Pull request by ryanjeffries**
Opening this pull request more for dialog, I had implemented this yesterday, we could merge some ideas.

Metrics have a configuration that is independent of the default conf and topic confs. Perhaps this configuration could default back to the default conf if values are not provided. This would also allow for a central metrics collection location rather than having to query against multiple influxes to build graphs.

Metrics would be flushed on a configurable interval, rather than sending influx a batch of metrics on every poll of kafka.

Ingestion count and parse error count would be a lifelong counter rather than a per package counter. This would allow for rate and derivative type queries and graphs. As well, this would considerably reduce the number of delivered sent to influx.

I tried to separate out metrics from the app in case, at a later time, a different means of submitting metrics was implemented, such as standard out or even Prometheus.

### CODE REVIEW

**Comment by stephane-martin** [comment]
To my mind there are two ways of reporting metrics:

- as I implemented it, kafka2influxdb (k2i) reports metrics in "logging way".

Each time some records are successfully pushed to influxdb, k2i reports the number of records. It "logs" the successfull push. If i understand influxdb doc (im not sure ;)), you can then derive the total count of ingested records with a continuous query that would SUM the individual pushes.

Advantages: simple to implement. No need to have "metric memory" in code.
Disadvantages: many writes to InfluxDB (if the batch size is big enough, it's not so important). Needs more work in InfluxDB to derive useful data.

- as you implemented it, k2i has some "metric memory" of what happened before. Periodically, the memory is flushed to InfluxDB

Advantages: the user can control how often the metrics get reported. k2i can directly report the total counts.
Disadvantages: a bit more complicated to implement. The reported "total counts" won't be monotonous in case k2i is restarted (back to 0).

I'm not sure which approach would be best.

**Comment by ryanjeffries** [comment]
The logging way, is already taken care of through log.Debug, by logging each successful batch, this is effectively double logging.

Influx can handle the sum of these metrics and the change of rate between point. Influx will compare the change of rate during a restart and handle accordingly.

**Comment by stephane-martin** [comment]
Could you adapt your PR to use go-kit/metrics (https://github.com/go-kit/kit/tree/master/metrics) ? This would effectively provide database abstraction.

**Comment by ryanjeffries** [comment]
that sounds good

**Pull request closed without merging**
